kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_kdl_factories
  fwd_kin_plugins:
    left_arm:
      default: KDLFwdKinChain
      plugins:
# //! [KDL FK config]
        KDLFwdKinChain:
          class: KDLFwdKinChainFactory
          config:
            base_link: torso_link #base_link
            tip_link: left_wrist_yaw_link #tool0
# //! [KDL FK config]
  
  inv_kin_plugins:
    left_arm:
      default: KDLInvKinChainLMA
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: torso_link # base_link
            tip_link: left_wrist_yaw_link # iiwa_tool0
        KDLInvKinChainNR:
          class: KDLInvKinChainNRFactory
          config:
            base_link: torso_link # base_link
            tip_link: left_wrist_yaw_link # iiwa_tool0
   
